services:
  # Backend service
  - type: web
    name: logic-length
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server/index.js
    envVars:
      - key: PORT
        value: 5002
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DIRECT_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false

  # Frontend service
  - type: web
    name: logic-length-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    spa: true
    envVars:
      - key: VITE_SERVER_URL
        value: https://logic-length.onrender.com
